name: ProjectSummary-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Test action code
    steps:
    - uses: actions/checkout@v2
    - name: Stub
      run: echo "Needs tests before I can do this"

  package-and-publish:
    runs-on: ubuntu-latest
    name: Replace and public the V.Latest label
    steps:
    - name: Delete tag
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git tag -d v.Latest
      continue-on-error: true

    - name: Public v.Latest tag
      run: |
        git tag -a -m "Project Summary Action CI release" v.Latest
        git push --follow-tags
