name: ProjectSummary-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-tag:
    runs-on: ubuntu-latest
    name: Test action code and tag V.Latest label
    steps:
    - uses: actions/checkout@v2

    - name: Run unit tests
      run: |
        cd src
        npm test

    - name: Delete tag
      run: git push --delete origin v.ci
      continue-on-error: true

    - name: Publish v.ci tag
      run: |
        git config user.email ${{ secrets.email }}
        git config user.name ${{ secrets.login }}
        git tag -a -m "ProjectSummary Action Latest CI release" v.ci
        git push --follow-tags
