name: ProjectSummary-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-tag:
    runs-on: ubuntu-latest
    name: Test action code and tag V.Latest label
    steps:
    - uses: actions/checkout@v2

    - name: Run unit tests
      run: echo "Needs tests before I can do this"

    - name: Delete tag
      run: |
        git push --delete origin v.ci
        #git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        #git tag -d v.Latest
        #git push --follow-tags
      continue-on-error: true

    - name: Publish v.ci tag
      run: |
        git config user.email ${{ secrets.email }}
        git config user.name ${{ secrets.login }}
        git tag -a -m "ProjectSummary Action Latest CI release" v.ci
        git push --follow-tags
