name: ProjectSummary-Test

on:
  project_card:
    types: [ created, moved, converted, edited, deleted ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    - name: Analyze project
      id: analyze
      uses: dmckinstry/ProjectSummary@v.ci
      with:
        login: dmckinstry
        repo: ProjectSummary
        project: ProjectSummaryTest
        token: TBD
        
    # Project column summary
    - name: Get the output
      run: echo "The output was ${{ steps.analyze.outputs.summary }}"
