name: ProjectSummary-Test

on:
  project_card:
    types: [ created, moved, converted, edited, deleted ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Analyze project
      id: analyze
      uses: dmckinstry/ProjectSummary@v.ci
      with:
        login: dmckinstry
        repo: ProjectSummary
        project: ProjectSummaryTest
        token: ${{ secrets.token }}

    # Project column summary
    - name: Get the output
      run: |
        echo "The output was ${{ steps.analyze.outputs.summary }}"
        echo "Summarized as markdown:"
        echo ${{ steps.analyze.outputs.markdownList
