name: ProjectSummary-Test

on:
  project_card:
    types: [ created, moved, converted, edited, deleted ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    - name: Analyze project
      id: hello
      uses: dmckinstry/ProjectSummary@V.Latest
      with:
        

    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
