name: ProjectSummary-Test

on:
  project_card:
    types: [ created, moved, converted, edited, deleted ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
