name: ProjectSummary-Test

on:
  project_card:
    types: [ created, moved, converted, edited, deleted ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Analyze project
      id: analyze
      uses: dmckinstry/ProjectSummary@v.ci
      with:
        login: dmckinstry
        repo: ProjectSummary
        project: ProjectSummaryTest
        token: ${{ secrets.token }}

  report-results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.1
      - name: Capture test results
        run: |
          echo "# Test Results\n"                             > test-results.md
          echo "## Markdown List\n"                           >> test-results.md
          echo "${{ steps.analyze.outputs.markdownList }}\n"  >> test-results.md
          echo "## Markdown List\n"                           >> test-results.md
          echo "``` JSON\n"                                   >> test-results.md
          echo "${{ steps.analyze.outputs.summary }}\n"       >> test-results.md
          echo #```"                                          >> test-results.md
          git add test-results.md
          git stage test-results.md
          git commit "Updated integration test results per ${{ github.run_id }}"
          git push
